deploy:
  stage: deploy
  image: dtzar/helm-kubectl:latest
  script:
    - echo $KUBE_CONFIG | base64 -d > config.yml
    - sed -i "s|IMAGE_TAG|$CI_COMMIT_SHA|g" k8s/deployment.yml
    - kubectl --kubeconfig=config.yml apply -f k8s/deployment.yml
  environment:
    name: production