pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kubectl
    image: lachlanevenson/k8s-kubectl:v1.25.0
    command:
    - sleep
    args:
    - infinity
    tty: true
  - name: docker
    image: docker:latest
    command:
    - sleep
    args:
    - infinity
    tty: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
'''
        }
    }

    stages {
        stage('Test') {
            steps {
                sh 'echo "Tests passed!"'
            }
        }

        stage('Build Image') {
            container('docker') {
                steps {
                    sh 'docker --version'
                    sh 'docker build -t ppkrasko/my-app-jenkins:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Deploy to K8s') {
            container('kubectl') {
                steps {
                    withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                        sh 'kubectl get nodes --insecure-skip-tls-verify'
                        sh 'kubectl apply -f k8s/deployment.yml --insecure-skip-tls-verify'
                    }
                }
            }
        }
    }
}